// Generated by CoffeeScript 1.7.1
(function() {
  var ScreenShot, Spooky, captures, urls;

  Spooky = require('spooky');

  ScreenShot = (function() {
    var analysis, next, _urls;

    _urls = [];

    function ScreenShot(urls) {
      var id, url;
      for (id in urls) {
        url = urls[id];
        _urls.push({
          id: id,
          url: url
        });
      }
      next.call(this);
    }

    next = function() {
      var url;
      url = _urls.pop();
      if (!(url.url === void 0 || url.id === void 0)) {
        return analysis.call(this, url.url, url.id);
      } else {
        return console.log("finish capture pages.");
      }
    };

    analysis = function(url, img_path) {
      var spooky;
      img_path = "captures/" + img_path + ".png";
      spooky = new Spooky({
        child: {
          transport: 'http'
        },
        casper: {
          logLevel: 'info',
          verbose: true
        }
      }, function(err) {
        var e;
        if (err) {
          e = new Error('Failed to initialize SpookyJS');
          e.details = err;
          throw e;
        }
        spooky.start(url);
        spooky.then([
          {
            img_path: img_path,
            url: url
          }, function() {
            this.capture(img_path);
            return emit("finish", url);
          }
        ]);
        return spooky.run(function() {
          return this.exit();
        });
      });
      spooky.on('error', function(e, stack) {
        console.error(e);
        if (stack) {
          return console.log(stack);
        }
      });
      spooky.on('console', function(line) {
        return console.log(line);
      });
      spooky.on('log', function(log) {
        if (log.space === 'remote') {
          return console.log(log.message);
        }
      });
      return spooky.on('finish', function(url) {
        console.log("> finish " + url);
        return next.call(this);
      });
    };

    return ScreenShot;

  })();

  urls = {
    135371: "http://juggly.cn/archives/135371.html",
    135370: "http://juggly.cn/archives/135370.html",
    135369: "http://juggly.cn/archives/135369.html",
    135368: "http://juggly.cn/archives/135368.html",
    135367: "http://juggly.cn/archives/135367.html"
  };

  captures = new ScreenShot(urls);

}).call(this);
